openapi: 3.0.0
info:
  version: 1.0.0
  title: Tassio's Resume API
  description: An API to present my professional information

servers:
  - url: https://x8ki-letl-twmt.n7.xano.io/api:hm7hZTrv

components:
  securitySchemes:
    { bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT } }
  schemas: {}
paths:
  /personal-info:
    get:
      description: Returns a list of artists 
      #  ----- Added lines  ----------------------------------------
      responses:
        '200':
          description: Successfully returned Tassio's personal details
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                    - email
                  properties:
                    linkedin_profile:
                      type: string
                    phone number:
                      type: string
                    email:
                      type: string
                    name:
                      type: string
                    twitter:
                      type: string