openapi: 3.0.0
info:
  version: 1.0.0
  title: Tassio's Resume API
  description: An API to present my professional information

servers:
  - url: https://x8ki-letl-twmt.n7.xano.io/api:hm7hZTrv

components:
  securitySchemes:
    { bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT } }
  schemas: {}
paths:
  /personal-info:
    {
      get:
        {
          summary: "Get Personal Info",
          description: "Get Personal Info\n<br /><br />\n<b>Authentication:</b> not required",
          tags: [personal-info],
          security: [],
          parameters: [],
          responses:
            {
              200:
                {
                  description: Success!,
                  content:
                    {
                      application/json:
                        { schema: { type: object, properties: {} } },
                    },
                },
              400:
                {
                  description: "Input Error. Check the request payload for issues.",
                },
              403:
                {
                  description: "Access denied. Additional priviledges are needed access the requested resource.",
                },
              404:
                {
                  description: "Not Found. The requested resource does not exist.",
                },
              429: { description: "Rate Limited. Too many requests." },
              500: { description: "Unexpected error" },
            },
        },
    }
    #  ---- /Added lines  ----------------------------------------
